apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  ports:
    - name: jenkins
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30036
  selector:
    app: jenkins
  type: NodePort