apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus-server
  name: nexus-server
spec:
  ports:
    - name: nexus
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30037
  selector:
    app: nexus-server
  type: NodePort